resources:
    App\Entity\User:
        attributes:
            normalization_context:
                groups: ['user_read']
            denormalization_context:
                groups: ['user_write']
